-- Fills database with dummies for testing

-- The ids are set to 101 and 102 because in spring autogenerated ids start from 1 which causes errors
-- if the database is filled with dummies that already have such id (now we can get to 100 without any errors).
-- In order for database to not throw any errors, please comment out the following methods.

INSERT INTO BOOKS (ID, TITLE, GENRE)
    VALUES (101, 'Title example 1', 'FICTION'),
    (102, 'Title example 2', 'NONFICTION');

INSERT INTO AUTHORS (ID, FIRST_NAME, LAST_NAME, BIRTH_DATE)
    VALUES (101, 'Name1', 'Surname1', '1991-01-01'),
    (102, 'Name2', 'Surname2', '1992-02-02');

INSERT INTO BOOK_AUTHORS (A_ID, B_ID)
    VALUES (101, 101),
    (101, 102),
    (102, 102);



