DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS BOOK_AUTHOR_LOOKUP;

CREATE TABLE BOOKS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    GENRE ENUM('FICTION', 'NONFICTION') NOT NULL
);

CREATE TABLE AUTHORS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    BIRTH_DATE DATE NOT NULL
);

CREATE TABLE BOOK_AUTHOR_LOOKUP (
    A_ID BIGINT NOT NULL,
    B_ID BIGINT NOT NULL,
    CONSTRAINT FOREIGN_KEY_AUTHOR FOREIGN KEY (A_ID) REFERENCES books(ID),
    CONSTRAINT FOREIGN_KEY_BOOK FOREIGN KEY (B_ID) REFERENCES authors(ID),
    PRIMARY KEY(A_ID, B_ID)
);