DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS BOOK_AUTHORS;

-- Create tables for the database

CREATE TABLE BOOKS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    GENRE ENUM('FICTION', 'NONFICTION') NOT NULL
);

CREATE TABLE AUTHORS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    BIRTH_DATE DATE NOT NULL
);

CREATE TABLE BOOK_AUTHORS (
    A_ID BIGINT NOT NULL,
    B_ID BIGINT NOT NULL,
    CONSTRAINT FOREIGN_KEY_AUTHOR FOREIGN KEY (A_ID) REFERENCES AUTHORS(ID),
    CONSTRAINT FOREIGN_KEY_BOOK FOREIGN KEY (B_ID) REFERENCES BOOKS(ID),
    PRIMARY KEY(A_ID, B_ID)
);